# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2017-06-02 00:21+0300\n"
"PO-Revision-Date: 2017-06-02 00:28+0300\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 1.8.7.1\n"
"Last-Translator: \n"
"Plural-Forms: nplurals=3; plural=(n==1?0:(((n%100>19)||((n%100==0)&&(n!=0)))?2:1));\n"
"Language: ro\n"

#: VM/BDL/BDCon.py:19 VM/UI/ChoosingItem.py:41
msgid "There are no items to sell"
msgstr "Nu există elemente de vânzare"

#: VM/BDL/BDCon.py:20 VM/UI/ChoosingItem.py:42
msgid "Message"
msgstr "Mesaj"

#: VM/BDL/DataSources/MySQLDB.py:60 VM/BDL/DataSources/MySQLDB.py:76
#: VM/BDL/DataSources/MySQLDB.py:91 VM/BDL/DataSources/MySQLDB.py:107
#: VM/BDL/DataSources/MySQLDB.py:123 VM/BDL/DataSources/MySQLDB.py:178
#: VM/UI/CheckPass.py:31 VM/Vending.py:40
msgid "Error"
msgstr "Eroare"

#: VM/BDL/DataSources/MySQLDB.py:60 VM/BDL/DataSources/MySQLDB.py:91
#: VM/BDL/DataSources/MySQLDB.py:107 VM/BDL/DataSources/MySQLDB.py:123
msgid "Database connection failed"
msgstr "Eroare la conectarea cu baza de date"

#: VM/BDL/DataSources/MySQLDB.py:76 VM/UI/CheckPass.py:31
msgid "There is errors in the configuration file. No section."
msgstr "Eroare de configurare. Nu există secțiunea"

#: VM/BDL/DataSources/MySQLDB.py:178
msgid "Database error"
msgstr "Eroare bazei de date"

#: VM/Errors.py:19
msgid "Close"
msgstr "Închide"

#: VM/KP/KPProvider.py:91
msgid "Error in recognition of note"
msgstr "Eroare in recunoașterea bancnotei"

#: VM/KP/KPProvider.py:106
msgid "Protocol version's setting error"
msgstr "Eroare de instalare a versiunei protocolului"

#: VM/KP/KPProvider.py:113
msgid "Error in request of notes' channels"
msgstr "Eroare de cerere a canalului bancnotei"

#: VM/KP/KPProvider.py:122
msgid "Error in notes' denomination reading"
msgstr "Eroare de citire a valoarei bancnotei"

#: VM/KP/KPProvider.py:129
msgid "Error in setting channels of notes receiving"
msgstr "Eroare de instalare a receptorului bancnotelor"

#: VM/KP/KPProvider.py:136
msgid "Engage procedure error"
msgstr "Eroare in procedura de lansare"

#: VM/KP/KPProvider.py:151
msgid "Device synchronization failed"
msgstr "Eroare in sincronizare dispozitivului"

#: VM/KP/KPProvider.py:288
msgid "Note receiver's port is not found"
msgstr "Portul a receptorului bancnotelor nu a fost găsit"

#: VM/KP/KPProvider.py:305
msgid "Devise not responding"
msgstr "Dispozitivul nu răspunde"

#: VM/UI/ChoosingItem.py:95
msgid "Select the model"
msgstr "Alegeti modelul"

#: VM/UI/ChoosingItem.py:96 VM/UI/ReceiveCash.py:50
msgid "Cancel"
msgstr "Anulare"

#: VM/UI/FinishWindow.py:33
msgid "The key was written successfully"
msgstr "Cheia este înregistrată cu succes"

#: VM/UI/FinishWindow.py:34
msgid "Thanks for purchase"
msgstr "Vă mulțumim pentru procurare"

#: VM/UI/GivingOutItem.py:29
msgid "Wait for delivery..."
msgstr "Asteptati emiterea"

#: VM/UI/GivingOutItem.py:36
msgid "Delivery error. Call techsupport, please."
msgstr "Eroare în emitere. Vă rugăm să contactați suportul tehnic."

#: VM/UI/ReceiveCash.py:47
msgid "Incomming cash"
msgstr "Suma întrodusă"

#: VM/UI/ReceiveCash.py:48
msgid "Pay"
msgstr "Plătiți"

#: VM/UI/ReceiveCash.py:49
msgid "Mashine does not give any odd money"
msgstr "Apparatul restul nu elibereaza"

#: VM/UI/ReceiveCash.py:51
msgid "Next"
msgstr "Mai departe"

#: VM/UI/ScanBrelok.py:70
msgid "Press the button \"Scan\""
msgstr "Apăsați butonul 'Scanați'"

#: VM/UI/ScanBrelok.py:71
msgid "and enclose your key"
msgstr "și apropiați cheia D-vstră"

#: VM/UI/ScanBrelok.py:72
msgid "to the scanner"
msgstr "de scaner"

#: VM/UI/ScanBrelok.py:73
msgid "Scanning..."
msgstr "Scanare"

#: VM/UI/ScanBrelok.py:74
msgid "Error!"
msgstr "Eroare!"

#: VM/UI/ScanBrelok.py:75
msgid "Scan"
msgstr "Scanați"

#: VM/UI/WriteBrelok.py:40
msgid "The key is given away"
msgstr "Cheia este eliberată"

#: VM/UI/WriteBrelok.py:41
msgid "Press 'Next'"
msgstr "Apăsați  'Mai departe'"

#: VM/UI/WriteBrelok.py:42
msgid "and enclose it to the scanner"
msgstr "și apropiați cheia de scaner"

#: VM/UI/WriteBrelok.py:43
msgid "Writing..."
msgstr "Înregistrare..."

#: VM/UI/WriteBrelok.py:44
msgid "Writing failed!"
msgstr "Înregistrarea eșuată."

#: VM/UI/WriteBrelok.py:45
msgid "Try again, please."
msgstr "Încercați încă o dată"

#: VM/UI/WriteBrelok.py:46
msgid "Write"
msgstr "Înscrie"

#: VM/Vending.py:39
msgid "Database connection error"
msgstr "Eroare la conectarea cu baza de date"
